/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.10.3.144 */
/* Module Version: 5.7 */
/* Tue Apr 23 14:35:04 2019 */

/* parameterized module instance */
pll_64M __ (.CLKI( ), .CLKI2( ), .SEL( ), .RST( ), .CLKOP( ), .LOCK( ));
