/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.10.3.144 */
/* Module Version: 7.5 */
/* Thu May 09 19:32:30 2019 */

/* parameterized module instance */
ble_packet_mem __ (.Clock( ), .ClockEn( ), .Reset( ), .WE( ), 
    .Address( ), .Data( ), .Q( ));
